spring:
  application:
    name: payment
  datasource:
    url: jdbc:mysql://localhost:3306/carrotTestDB?serverTimezone=Asia/Seoul
    username: test
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  kafka:
    consumer:
      group-id: payment
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: localhost:9092
eureka:
  client:
    service-url:
      defaultUrl: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true # ???

  
api:
  key: test_sk_mBZ1gQ4YVXjawyl0aAq68l2KPoqN

server:
  port: 4000
